# Define networks
networks:
  nest-api-network:
    name: nest-api-network
    driver: bridge
    external: true

# Define volumes
volumes:
  nest-postgres-data:
    name: c3757815ab775c267ba292a6ef9e33b50539d051
    external: false
  redisinsight-data:
    name: d1b2cd4ab4218657fc0a57752c34503945d8a126
    external: false
  meilisearch-data:
    name: 74c4ac18c0f7ada9f203d79f5e1d7bdf4356851f
    external: false


# Define services
services:
  nest-postgres-server:
    container_name: nest-postgres-server  
    image: postgres:17.4
    volumes:
      - nest-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassword@123
    ports:
      - '5432:5432'
    networks:
      - nest-api-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nest-api-server:
    container_name: nest-api-server
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    working_dir: /app
    volumes:
      - ./html/:/app
    environment:
      NODE_ENV: development
      APP_DEBUG: true
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - nest-api-network
    depends_on:
      - nest-postgres-server
      - nest-redis-server
      - nest-meilisearch-server
    entrypoint: [ "/bin/bash", "./entrypoint.sh", "development" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nest-redis-server:
    container_name: nest-redis-server
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    networks:
      - nest-api-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nest-redisinsight-server:
      container_name: nest-redisinsight-server
      image: redis/redisinsight:2.54
      ports:
        - "5540:5540"
      volumes:
        - redisinsight-data:/data
      networks:
        - nest-api-network

  nest-meilisearch-server:
    container_name: nest-meilisearch-server
    image: getmeili/meilisearch:v1.32.2
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - nest-api-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

