# Define networks
networks:
  nest-api-network:
    name: nest-api-network
    driver: bridge
    external: true

# Define volumes
volumes:
  nest-postgres-data:
    name: c3757815ab775c267ba292a6ef9e33b50539d051
    external: false
  nest-mailpit-data:
    name: 1d96836f31e438ed12bee2c044c101b5a56201a0
    external: false
  redisinsight-data:
    name: d1b2cd4ab4218657fc0a57752c34503945d8a126
    external: false
  kafka-data:
    name: e4a0ba05475371d08384862ba6bfdf29b27b7880
    external: false
  meilisearch-data:
    name: 74c4ac18c0f7ada9f203d79f5e1d7bdf4356851f
    external: false


# Define services
services:
  nest-postgres-server:
    container_name: nest-postgres-server  
    image: postgres:17.4
    volumes:
      - nest-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassword@123
    ports:
      - '5433:5432'
    networks:
      - nest-api-network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


  nest-api-server:
    container_name: nest-api-server
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    working_dir: /app
    volumes:
      - ./html/:/app
    environment:
      NODE_ENV: development
      APP_DEBUG: true
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - nest-api-network
    depends_on:
      - nest-postgres-server
      - nest-mailpit-server
      - nest-redis-server
      - kafka-server
    entrypoint: [ "/bin/bash", "./entrypoint.sh", "development" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nest-mailpit-server:
    container_name: nest-mailpit-server
    image: axllent/mailpit:v1.23
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - nest-mailpit-data:/data
    networks:
      - nest-api-network
    healthcheck:
      test: [ 'CMD-SHELL', 'nc -z localhost 1025' ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nest-redis-server:
    container_name: nest-redis-server
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    networks:
      - nest-api-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nest-redisinsight-server:
      container_name: nest-redisinsight-server
      image: redis/redisinsight:latest
      ports:
        - "5540:5540"
      volumes:
        - redisinsight-data:/data
      networks:
        - nest-api-network

  
  kafka-server:
    container_name: kafka-server
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkafkaClusterId1234567890
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - nest-api-network
    restart: unless-stopped

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - nest-api-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

